
[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
# style = "Regular"
style = "Light"

[font.offset]
y = 2

[window]
decorations = "Buttonless"
opacity = 0.8
# option_as_alt = "OnlyLeft"
blur = true

[keyboard]
bindings = [
  # other bindings, and this one:
  { key = "Space", mods = "Alt", action = "None" }
]

[general]
import = [
    # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
    # "~/.config/alacritty/themes/themes/nordic.toml"
]
