require("user.plugins.packer")
require("user.plugins.nvimtree")
require("user.plugins.treesitter")
require("user.plugins.colors")
require("user.plugins.gitsigns")
require("user.plugins.autopairs")
require("user.plugins.cmp")
require("user.plugins.lsp")
