require("user.setup_default_options")
require("user.setup_default_keymaps")
require("user.setup_plugins")
require("user.setup_treesitter")
require("user.setup_colors")
require("user.setup_cmp")
require("user.setup_lsp")
