require("user.default_options")
require("user.default_keymaps")
require("user.plugins")
require("user.nvimtree")
require("user.treesitter")
require("user.colors")
require("user.cmp")
require("user.lsp")
